services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Artem2502
      POSTGRES_DB: cachedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cachedb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Artem2502@postgres:5432/cachedb
      REDIS_URL: redis://redis:6379
      CACHE_TTL: "300"
      FLUSH_INTERVAL: "5"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
